export const MAX_TITLE_LENGTH = 100
export const MAX_BODY_LENGTH = 100
export const MAX_CHAT_INPUT_LENGTH = 100
export const ARTICLES_PER_PAGE = 20
export const MAX_CONVERSATION_ROUNDS = 10
export const MAX_HISTORY_LENGTH = 20
export const MAX_HISTORY_CONTENT_LENGTH = 2000
